# Generated by Django 4.1.4 on 2022-12-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('2013', '2013'), ('2014', '2014'), ('2015', '2015')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='car', max_length=50, verbose_name='Title'),
        ),
    ]
