# Generated by Django 4.1.4 on 2023-01-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_employee_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.car'),
        ),
    ]
