# Generated by Django 4.1.4 on 2023-01-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_employee_relation_employee_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['name'], 'verbose_name': 'Project'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Art', 'Art'), ('Design', 'Design'), ('Food', 'Food'), ('Games', 'Games')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='project', max_length=50, verbose_name='Project Title'),
        ),
    ]
