# Generated by Django 4.1.4 on 2023-01-06 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_car_options_remove_car_color_alter_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='current_situation',
        ),
    ]
