# Generated by Django 4.1.4 on 2023-01-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_price_car_current_situation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='category',
        ),
    ]
