# Generated by Django 4.1.4 on 2023-01-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_model_car_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Project',
        ),
    ]
