# Generated by Django 4.1.4 on 2023-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Design', 'Design'), ('Food', 'Food'), ('Games', 'Games')], default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
