# Generated by Django 4.1.4 on 2023-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_project_category_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_situation',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
