# Generated by Django 4.1.4 on 2023-01-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_remove_project_start_date_project_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='target',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='project', max_length=50, verbose_name='Project Title'),
        ),
    ]
