# Generated by Django 4.1.4 on 2023-01-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_project_target_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
