# Generated by Django 4.1.4 on 2023-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_remove_project_start_date_project_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Project Title'),
        ),
    ]
