# Generated by Django 4.1.4 on 2023-01-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_project_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='user',
        ),
    ]
