# Generated by Django 4.1.4 on 2023-01-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_remove_project_user_created_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='created_project',
        ),
    ]
