# Generated by Django 4.1.4 on 2023-01-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_funded_project_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_situation',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
